Mongoose@6 (#509)
* migrate for mongoose@6
* update also mongomock
* update inmemory initialization
* fix bug that makes now visible after mongoose update

if Result:dut object was same time with duts -
object result was generated with extra dut.

* create user explicitly for each user tests
replace obsoleted nModified with modifiedCount property
* fix loan test
* CI store logs even test fails
* replace deprecated uuid usage

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -48,11 +48,14 @@ jobs:
     - name: api tests
       run: |
         MOCHA_FILE=junit/apitests.xml grunt apitests --silent
+    - name: cluster tests
+      run: |
         MOCHA_FILE=junit/clustertests.xml grunt clustertests --silent
     - name: lint
       run: |
         npm run lint
     - uses: actions/upload-artifact@v2.2.4
+      if: success() || failure()    # run this step even if previous step failed
       with:
         # Artifact name
         name: logs-${{ matrix.node-version }}
